// 
// Create by kong on 2024/5/29
// Copyright 2024 Beijing Xinchangcheng Technology Development Co., Ltd.
//
#ifndef CYBERLIB_BUILD_SIGNED_ATTRIBUTES_H
#define CYBERLIB_BUILD_SIGNED_ATTRIBUTES_H

#include <string>
#include <openssl/x509.h>

namespace iwall {

class SignedAttributes {
public:
    // The messageType attribute specifies the type of operation performed
    // by the transaction.  This attribute MUST be included in all PKI
    // messages.  The following message types are defined:
    // PKCSReq (19) -- PKCS#10 [RFC2986] certificate request
    // CertRep (3) -- Response to certificate or CRL request
    // GetCertInitial (20) -- Certificate polling in manual enrollment
    // GetCert (21) -- Retrieve a certificate
    // GetCRL (22) -- Retrieve a CRL
    enum MessageType {
        UnKnown = 0,
        PKCSReq = 19,
        CertRep = 3,
        GetCertInitial = 20,
        GetCert = 21,
        GetCRL = 22,
    };

    // All response messages MUST include transaction status information,
    // which is defined as pkiStatus attribute:
    // SUCCESS (0) -- request granted
    // FAILURE (2) -- request rejected.  When pkiStatus is FAILURE, the
    // failInfo attribute, as defined in Section 3.1.1.4, MUST also be present.
    // PENDING (3) -- request pending for manual approval
    enum PKIStatus {
        SUCCESS = 0,
        FAILURE = 2,
        PENDING = 3,
    };

    // The failInfo attribute MUST contain one of the following failure reasons:
    // badAlg (0) -- Unrecognized or unsupported algorithm identifier
    // badMessageCheck (1) -- integrity check failed
    // badRequest (2) -- transaction not permitted or supported
    // badTime (3) -- The signingTime attribute from the PKCS#7
    // authenticatedAttributes was not sufficiently close to the system time.
    // badCertId (4) -- No certificate could be identified matching the provided criteria
    // Undefined failInfo attributes are treated as an error.
    enum FailInfo {
        BadAlg          = 0,
        BadMessageCheck = 1,
        BadRequest      = 2,
        BadTime         = 3,
        BadCertId       = 4,
        BadUnKnown      = 5,
    };

    // Life Cycle
    SignedAttributes();
    explicit SignedAttributes(struct stack_st_X509_ATTRIBUTE *attributes);
    ~SignedAttributes();

    explicit SignedAttributes(MessageType messageType);

    // Class Variables
    std::string transaction_id() { return transaction_id_; }
    MessageType message_type() { return message_type_; }
    PKIStatus   pki_status() { return pki_status_; }
    FailInfo    fail_info() { return fail_info_; }
    std::string fail_info_txt() { return fail_info_txt_; }
    std::string sender_nonce() { return sender_nonce_; }
    std::string recipient_nonce() { return recipient_nonce_; }
    std::string signing_time() { return signing_time_; }

    // Class method
    STACK_OF(X509_ATTRIBUTE) *EncodeAttributes();
    bool DecodeAttributes(const struct stack_st_X509_ATTRIBUTE *attributes);

    void Print() const;
    std::string ToString();

private:
    // A PKI operation is a transaction consisting of the messages exchanged
    // between a requester and the server.  The transaction identifier is a
    // string generated by the client when starting a transaction.  The
    // client MUST generate a unique string as the transaction identifier,
    // which MUST be used for all PKI messages exchanged for a given
    // enrollment, encoded as a PrintableString.
    std::string transaction_id_;

    // The messageType attribute specifies the type of operation performed
    // by the transaction.  This attribute MUST be included in all PKI
    // messages.  The following message types are defined:
    // PKCSReq (19) -- PKCS#10 [RFC2986] certificate request
    // CertRep (3) -- Response to certificate or CRL request
    // GetCertInitial (20) -- Certificate polling in manual enrollment
    // GetCert (21) -- Retrieve a certificate
    // GetCRL (22) -- Retrieve a CRL
    MessageType message_type_ = GetCert;

    // All response messages MUST include transaction status information,
    // which is defined as pkiStatus attribute:
    // SUCCESS (0) -- request granted
    // FAILURE (2) -- request rejected.  When pkiStatus is FAILURE, the
    // failInfo attribute, as defined in Section 3.1.1.4, MUST also be present.
    // PENDING (3) -- request pending for manual approval
    PKIStatus pki_status_ = FAILURE;

    // The failInfo attribute MUST contain one of the following failure reasons,
    // See FailInfo enum.
    FailInfo fail_info_ = BadUnKnown;
    std::string fail_info_txt_;

    // The attributes of senderNonce and recipientNonce are a 16 byte random
    // number generated for each transaction.  These are intended to prevent
    // replay attacks.
    // When a requester sends a PKI message to the server, a senderNonce
    // MUST be included in the message.
    // The recipient SHOULD copy the senderNonce into the recipientNonce of
    // the reply as a proof of liveliness.
    // The requester SHOULD verify that the recipientNonce of the reply
    // matches the senderNonce it sent in the request.
    std::string sender_nonce_;
    std::string recipient_nonce_;

    // The signingTime attribute type is intended for PKCS #7 digitally
    // signed data.  It specifies the time at which the signer (purportedly)
    // performed the signing process.
    // A signing-time attribute must have a single attribute value.
    std::string signing_time_;

    // Attributes
    STACK_OF(X509_ATTRIBUTE) *attributes_ = nullptr;

};
}


#endif //CYBERLIB_BUILD_SIGNED_ATTRIBUTES_H
